### ISSUE TITLE
Add support for picking up hostname and id in beanstalkd 1.9+

### ISSUE THREAD

**Issue by svisser** [seveas/azuki#6]
No rush for this but I noticed that [beanstalkd 1.9 added support][2] for hostname and id in the global stats:

> - add a unique id and hostname to stats output ([#156][1])

You can see the commit here: https://github.com/qualtrics/beanstalkd/commit/d5ffd665048ef7e3fbac4fff002073e487820dea.

While not all stats output is useful, these values can be useful when managing many beanstalkd instances with azuki.

[1]: https://github.com/kr/beanstalkd/pull/156
[2]: http://kr.github.io/beanstalkd/2013/04/14/1.9-release-notes.html

**Comment by seveas** [comment]
Done in 7ba625f1
