### ISSUE TITLE
Add support for Python 3.x

### ISSUE THREAD

**Issue by svisser** [seveas/azuki#8]
This project currently fails to pass for Python 3.x support (http://caniusepython3.com/project/azuki).

Once support for Python 3.x is provided for beanstalkc (https://github.com/earl/beanstalkc/issues/33) we can verify that this package works in Python 3.x as well. Mainly opening this issue to keep track of things (I may write a patch myself if any changes are needed).

**Comment by seveas** [comment]
Done in a60f5e07 using a python3-compatible beanstalkc.
